### ISSUE TITLE
a problem about "Flowlines From Stream Network"

### ISSUE THREAD

**Issue by Madrame3** [yingkui2003/PalaeoIce#1]
It seems to be a running error which i can't figure out how to do it right

The DEM projection is: WGS_1984_UTM_Zone_43N
The moraine cross section projection is: WGS_1984_UTM_Zone_43N
Both DEM and moraine cross section have the same projected coordinate system: WGS_1984_UTM_Zone_43N
Traceback (most recent call last):
  File "C:\Users\madra\PalaeoIce-main\PalaeoIce2.0\python\CenterlineFromStream.py", line 541, in <module>
    Flowline_from_Stream_Network (InputDEM, InputMoraineorCrossSection, StreamThresholdKM2, TributaryThresholdKM2, TributaryRatio, StreamLine, outWatershed)
  File "C:\Users\madra\PalaeoIce-main\PalaeoIce2.0\python\CenterlineFromStream.py", line 190, in Flowline_from_Stream_Network
    cellsize_int = int(cellsize.getOutput(0))
ValueError: invalid literal for int() with base 10: '27.6350531049685'

Failed script Flowlines From Stream Network...
Failed to execute (DeriveFlowlineFromStreamNetwork).

**Comment by yingkui2003** [comment]
The Python file is updated now. You can download the whole toolbox and rerun the tool. Please let me know if you have other questions.
